### ISSUE TITLE
Récupération IP et hostname ? 

### ISSUE THREAD

**Issue by w4zu** [toorop/banisher#3]
Hello,
Je voudrais savoir si c’était possible de récupérer le hostname dans la ligne que catch banisher dans les logs par exemple pour pure-ftpd.
Je m'explique : 
Dans les logs messages, parfois pure-ftpd ne récupère pas l'ip mais le hostname de la machine qui se connecte  par exemple : 
```sh
May 14 18:26:56 zeee pure-ftpd: (?@37.122.179.131) [WARNING] Authentication failed for user [root]
May 15 08:51:20 zeee pure-ftpd: (?@39.43.14.232) [WARNING] Authentication failed for user [Admin]
May 15 17:15:18 zeee pure-ftpd: (?@torseedslu) [WARNING] Authentication failed for user [anonymous]
May 17 07:23:25 zeee pure-ftpd: (?@wsip-64-207-236-98.tu.ok.cox.net) [WARNING] Authentication failed for user [www-data]
```
Je voudrais rajouter la règle suivantes : 
```yml
  - name: pure-ftpd
    match: pure-ftpd:.*Authentication failed*
    IPpos: 0
```

Est-ce possible que cela fonctionne ou pas du tout ? ou il faut faire une modification sur banishier  ?

Merci :+1:

**Comment by toorop** [comment]
Non ça na va pas fonctionner, le masque de recherche est une IP (v4).
Par ailleurs il faudrait ensuite faire la résolution pour retomber sur l'IP et je suis a peut persuadé que ça ne matcherait pas forcement la bonne IP.
Il n'y a pas une option dans pure-ftpd pour qu'il ne resolve pas le reverse dans les logs ?
A priori oui: https://serverfault.com/questions/532129/pure-ftpd-log-ip-adresses (c'est un peu vieux mais bon... ;))
